binary_config = {
    r"S-06HGA.*": {
        "threshold": 30,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (3, 3),
    },
    r"S-08HGA.*": {
        "threshold": 30,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (3, 3),
    },
    r"S-13DG.*": {
        "threshold": 70,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (3, 3),
    },
    r"S-24ABH.*": {
        "threshold": 190,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (10, 10),
    },
    r"S-30KBM.*": {
        "threshold": 220,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (10, 10),
    },
    r"S-32BBM.*": {
        "threshold": 200,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (10, 10),
    },
    r"S-34VBM.*": {
        "threshold": 200,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (10, 10),
    },
    r"S-35EBMUD-Q.*": {
        "threshold": 170,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (10, 10),
    },
    r"AUTO-FGLR05EL.*": {
        "threshold": 220,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (5, 5),
    },
    r"FMLR06BU.*": {
        "threshold": 220,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (10, 10),
    },
    r"0945W.*": {
        "threshold": 190,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (20, 20),
    },
    r"0945A.*": {
        "threshold": 190,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (100, 40),
    },
    r"0945Y.*": {
        "threshold": 190,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (100, 40),
    },
    r"0945U.*": {
        "threshold": 190,
        "binary_type": "THRESH_BINARY_INV",
        "open_close_type": "MORPH_OPEN",
        "struct_element_tuple": (100, 40),
    },
    r"BOB1J37H-AA.*": {
        "threshold": 80,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (10, 10),
    },
    r"3535.*": {
        "threshold": 100,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (10, 10),
    },
    r"BWB1B29A.*": {
        "threshold": 30,
        "binary_type": "THRESH_BINARY",
        "open_close_type": "MORPH_CLOSE",
        "struct_element_tuple": (10, 10),
    },
}
