image_config = {
    r"S-06HGA.*": {
        "refer_light": "L4",
        "light_list": ["L1", "L2", "L4"],
        "die_height": 80,
        "die_width": 54,
        "margin_x": 5,
        "margin_y": 5,
        "L1_offset": (0, 0),
    },
    r"S-08HGA.*": {
        "refer_light": "L4",
        "light_list": ["L1", "L2", "L4", "L8"],
        "die_height": 110,
        "die_width": 80,
        "margin_x": 5,
        "margin_y": 5,
        "L1_offset": (0, 0),
    },
    r"S-13DG.*": {
        "refer_light": "L4",
        "light_list": ["L1", "L2", "L4", "L8"],
        "die_height": 210,
        "die_width": 178,
        "margin_x": 5,
        "margin_y": 5,
        "L1_offset": (0, 0),
    },
    r"S-24ABH.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2", "L4", "L8"],
        "die_height": 372,
        "die_width": 250,
        "margin_x": 8,
        "margin_y": 8,
        "L1_offset": (0, 0),
    },
    r"S-30KBM.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2", "L4", "L8"],
        "die_height": 387,
        "die_width": 195,
        "margin_x": 15,
        "margin_y": 15,
        "L1_offset": (0, 0),
    },
    r"S-32BBM.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2", "L4"],
        "die_height": 490,
        "die_width": 148,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"S-34VBM.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2", "L4"],
        "die_height": 532,
        "die_width": 240,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"S-35EBMUD-Q.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2", "L4", "L8"],
        "die_height": 570,
        "die_width": 324,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"AUTO-FGLR05EL.*": {
        "refer_light": "L4",
        "light_list": ["L3", "L4"],
        "die_height": 54,
        "die_width": 54,
        "margin_x": 5,
        "margin_y": 5,
        "L1_offset": (0, 0),
    },
    r"FMLR06BU.*": {
        "refer_light": "L4",
        "light_list": ["L4", "L6"],
        "die_height": 82,
        "die_width": 82,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"0945W.*": {
        "refer_light": "IMAGE1",
        "light_list": ["IMAGE1", "IMAGE2", "IMAGE3", "IMAGE4"],
        "die_height": 140,
        "die_width": 740,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"0945A.*": {
        "refer_light": "IMAGE1",
        "light_list": ["IMAGE1", "IMAGE2", "IMAGE3", "IMAGE4"],
        "die_height": 140,
        "die_width": 740,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"0945Y.*": {
        "refer_light": "IMAGE1",
        "light_list": ["IMAGE1", "IMAGE2", "IMAGE3", "IMAGE4"],
        "die_height": 147,
        "die_width": 714,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"0945U.*": {
        "refer_light": "IMAGE1",
        "light_list": ["IMAGE1", "IMAGE2", "IMAGE3", "IMAGE4"],
        "die_height": 150,
        "die_width": 720,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"BOB1J37H-AA.*": {
        "refer_light": "L1",
        "light_list": ["L1", "L2"],
        "die_height": 586,
        "die_width": 586,
        "margin_x": 10,
        "margin_y": 10,
        "L1_offset": (0, 0),
    },
    r"3535.*": {
        "refer_light": "L2",
        "light_list": ["L1", "L2"],
        "die_height": 576,
        "die_width": 576,
        "margin_x": 20,
        "margin_y": 20,
        "L1_offset": (0, 0),
    },
    r"BWB1B29A.*": {
        "refer_light": "L1",
        # "light_list": ["L1", "L2"],
        "light_list": ["L1", ],
        "die_height": 480,
        "die_width": 450,
        "margin_x": 20,
        "margin_y": 20,
        "L1_offset": (0, 0),
    },
}
