# YOLOv5 ? by Ultralytics, AGPL-3.0 license
# COCO128 dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: python train.py --data coco128.yaml
# parent
# ©À©¤©¤ yolov5
# ©¸©¤©¤ datasets
#     ©¸©¤©¤ coco128  ¡û downloads here (7 MB)

nc: 2
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /var/cdy_data/obj_det/BGB1Q42E-D_train_val_v2 # dataset root dir
train: train  # train images (relative to 'path') 128 images
val: val  # val images (relative to 'path') 128 images
test:  # test images (optional)

# Classes
names:
  0: good
  1: location